[package]
name = "block_chain"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
sha2 = "0.10.8"
secp256k1 = { version = "0.30.0", features = ["hashes"] }
rand = "0.8.5"
colored = "2.2.0"